name = "antech-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.antech.store", zone_name = "antech.store" }
]

[env.production.vars]
ENVIRONMENT = "production"

