name = "antech-worker"
main = "src/index.ts"
compatibility_date = "2024-11-14"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "api.antech.store/*", zone_name = "antech.store" }
]

[env.production.vars]
ENVIRONMENT = "production"

